# Generated by Django 5.1.4 on 2025-03-06 09:04

import hodimlar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hodimlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='admin_users_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='hodim',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[hodimlar.models.validate_phone_number]),
        ),
    ]
