# Generated by Django 5.1.4 on 2025-03-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hodimlar', '0003_alter_adminuser_groups_alter_hodim_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hodim',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Hodim', 'verbose_name_plural': 'Hodimlar'},
        ),
        migrations.AlterUniqueTogether(
            name='hodim',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='hodim',
            name='lavozim',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='hodim',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'phone_number'), name='unique_hodim'),
        ),
    ]
