# Generated by Django 5.1.3 on 2024-12-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ishchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('familiya', models.CharField(max_length=50)),
                ('yosh', models.IntegerField()),
                ('jinsi', models.CharField(choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=10)),
                ('telefon', models.CharField(max_length=15)),
                ('lavozim', models.CharField(max_length=50)),
                ('ish_soatlari', models.FloatField(default=0)),
                ('soatlik_tarif', models.FloatField(default=10000)),
            ],
        ),
    ]
