# Generated by Django 5.1.3 on 2024-12-02 07:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishchilar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lavozim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name='Lavozim nomi')),
            ],
            options={
                'verbose_name': 'Lavozim',
                'verbose_name_plural': 'Lavozimlar',
            },
        ),
        migrations.AlterModelOptions(
            name='ishchi',
            options={'verbose_name': 'Ishchi', 'verbose_name_plural': 'Ishchilar'},
        ),
        migrations.RemoveField(
            model_name='ishchi',
            name='ish_soatlari',
        ),
        migrations.RemoveField(
            model_name='ishchi',
            name='soatlik_tarif',
        ),
        migrations.AddField(
            model_name='ishchi',
            name='ishga_kirgan_sana',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Ishga kirgan sana'),
        ),
        migrations.AlterField(
            model_name='ishchi',
            name='familiya',
            field=models.CharField(max_length=50, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='ishchi',
            name='ism',
            field=models.CharField(max_length=50, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='ishchi',
            name='jinsi',
            field=models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=10, verbose_name='Jinsi'),
        ),
        migrations.AlterField(
            model_name='ishchi',
            name='lavozim',
            field=models.CharField(max_length=100, verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='ishchi',
            name='telefon',
            field=models.CharField(max_length=15, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='ishchi',
            name='yosh',
            field=models.PositiveIntegerField(verbose_name='Yosh'),
        ),
        migrations.CreateModel(
            name='IshHaqqi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oy', models.CharField(max_length=20, verbose_name='Oy')),
                ('jami_ish_soati', models.FloatField(default=0.0, verbose_name='Jami ish soati')),
                ('tarif', models.FloatField(default=0.0, verbose_name='Tarif (soatlik)')),
                ('jami_ish_haqi', models.FloatField(default=0.0, verbose_name='Jami ish haqi')),
                ('ishchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ish_haqqi', to='ishchilar.ishchi')),
            ],
            options={
                'verbose_name': 'Ish haqi',
                'verbose_name_plural': 'Ish haqlari',
            },
        ),
        migrations.CreateModel(
            name='IshVaqti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kun', models.DateField(verbose_name='Kun')),
                ('boshlanish_vaqti', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('tugash_vaqti', models.TimeField(verbose_name='Tugash vaqti')),
                ('ishchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ish_vaqtlari', to='ishchilar.ishchi')),
            ],
            options={
                'verbose_name': 'Ish vaqti',
                'verbose_name_plural': 'Ish vaqtlar',
            },
        ),
    ]
