# Generated by Django 5.1.4 on 2024-12-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishchilar', '0003_ishchiishsoati_remove_ishchi_yosh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ishvaqti',
            name='boshlanish_vaqti',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='ishvaqti',
            name='kun',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ishvaqti',
            name='tugash_vaqti',
            field=models.TimeField(),
        ),
    ]
