# Generated by Django 5.1.4 on 2025-03-08 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hodimlar', '0002_alter_adminuser_groups_alter_hodim_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='admin_users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='hodim',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^\\+998\\d{9}$', "Telefon raqami +998 formatida va 9 ta raqamdan iborat bo'lishi kerak")]),
        ),
    ]
