# Generated by Django 4.0.10 on 2025-03-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hodimlar', '0005_alter_hodim_lavozim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hodim',
            name='age',
        ),
        migrations.AddField(
            model_name='hodim',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
