# Generated by Django 4.0.10 on 2025-11-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hodimlar', '0006_remove_hodim_age_hodim_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hodim',
            name='lavozim',
            field=models.CharField(choices=[('Tikuvchi', 'Tikuvchi'), ('Orta kesuvchi', 'Orta kesuvchi'), ('Kesuvchi', 'Kesuvchi'), ('Mexanik', 'Mexanik'), ('Ish boshqaruvchi', 'Ish boshqaruvchi')], default='Tikuvchi', max_length=50),
        ),
    ]
