# Generated by Django 4.0.10 on 2025-11-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hodimlar', '0007_alter_hodim_lavozim'),
    ]

    operations = [
        migrations.AddField(
            model_name='hodim',
            name='card_uid',
            field=models.CharField(blank=True, help_text='RFID karta UID', max_length=50, null=True, unique=True),
        ),
    ]
