# Generated by Django 4.0.10 on 2025-11-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hodimlar', '0008_hodim_card_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetsSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('credentials_json', models.TextField(blank=True, help_text='Google Service Account credentials JSON', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Sheets Settings',
                'verbose_name_plural': 'Google Sheets Settings',
            },
        ),
    ]
