# Generated by Django 5.2.8 on 2025-11-28 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hodimlar', '0009_googlesheetssettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='hodim',
            name='bolim',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Bo'lim"),
        ),
        migrations.AddField(
            model_name='hodim',
            name='oylik',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Oylik maosh'),
        ),
        migrations.AlterField(
            model_name='hodim',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator("^[a-zA-Z\\s']+$", "Ism faqat harflar va ' belgisidan iborat bo'lishi kerak")]),
        ),
        migrations.AlterField(
            model_name='hodim',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator("^[a-zA-Z\\s']+$", "Familiya faqat harflar va ' belgisidan iborat bo'lishi kerak")]),
        ),
    ]
